---
# handlers file for cesnet.pi_docker

- name: "PRIVACYIDEA Restart"
  community.docker.docker_compose_v2:
    project_src: "{{ privacyidea_path }}"
    state: restarted
  listen: "docker privacyidea restart"
